/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface HONEYPRODUCTIONInterface extends ethers.utils.Interface {
  functions: {
    "getHoneyInfo(uint256)": FunctionFragment;
    "getProducerInfo(address)": FunctionFragment;
    "modifyInfo(uint256,uint256,string)": FunctionFragment;
    "owner()": FunctionFragment;
    "permitAccess(address)": FunctionFragment;
    "permitted(address)": FunctionFragment;
    "producePackage(uint256,string)": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "revokeAccess(address)": FunctionFragment;
    "sellProduct(uint256)": FunctionFragment;
    "serialNumber()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "getHoneyInfo",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProducerInfo",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "modifyInfo",
    values: [BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "permitAccess",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "permitted", values: [string]): string;
  encodeFunctionData(
    functionFragment: "producePackage",
    values: [BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revokeAccess",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "sellProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "serialNumber",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "getHoneyInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProducerInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "modifyInfo", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "permitAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "permitted", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "producePackage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revokeAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "sellProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "serialNumber",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
}

export type OwnershipTransferredEvent = TypedEvent<
  [string, string] & { previousOwner: string; newOwner: string }
>;

export class HONEYPRODUCTION extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: HONEYPRODUCTIONInterface;

  functions: {
    getHoneyInfo(
      _serialNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [
        [BigNumber, BigNumber, BigNumber, string, string, boolean] & {
          serialNumber: BigNumber;
          packagingDate: BigNumber;
          quantityWeight: BigNumber;
          honeyType: string;
          Producer: string;
          sold: boolean;
        }
      ]
    >;

    getProducerInfo(
      _producerAddress: string,
      overrides?: CallOverrides
    ): Promise<[BigNumber[]]>;

    modifyInfo(
      _serialNumber: BigNumberish,
      _quantityWeight: BigNumberish,
      _honeyType: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    permitAccess(
      _producerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    permitted(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    producePackage(
      _quantityWeight: BigNumberish,
      _honeyType: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    revokeAccess(
      _producerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    sellProduct(
      _serialNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    serialNumber(overrides?: CallOverrides): Promise<[BigNumber]>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  getHoneyInfo(
    _serialNumber: BigNumberish,
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, BigNumber, BigNumber, string, string, boolean] & {
      serialNumber: BigNumber;
      packagingDate: BigNumber;
      quantityWeight: BigNumber;
      honeyType: string;
      Producer: string;
      sold: boolean;
    }
  >;

  getProducerInfo(
    _producerAddress: string,
    overrides?: CallOverrides
  ): Promise<BigNumber[]>;

  modifyInfo(
    _serialNumber: BigNumberish,
    _quantityWeight: BigNumberish,
    _honeyType: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  permitAccess(
    _producerAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  permitted(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  producePackage(
    _quantityWeight: BigNumberish,
    _honeyType: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  renounceOwnership(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  revokeAccess(
    _producerAddress: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  sellProduct(
    _serialNumber: BigNumberish,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  serialNumber(overrides?: CallOverrides): Promise<BigNumber>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    getHoneyInfo(
      _serialNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, BigNumber, BigNumber, string, string, boolean] & {
        serialNumber: BigNumber;
        packagingDate: BigNumber;
        quantityWeight: BigNumber;
        honeyType: string;
        Producer: string;
        sold: boolean;
      }
    >;

    getProducerInfo(
      _producerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber[]>;

    modifyInfo(
      _serialNumber: BigNumberish,
      _quantityWeight: BigNumberish,
      _honeyType: string,
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    permitAccess(
      _producerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    permitted(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    producePackage(
      _quantityWeight: BigNumberish,
      _honeyType: string,
      overrides?: CallOverrides
    ): Promise<void>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    revokeAccess(
      _producerAddress: string,
      overrides?: CallOverrides
    ): Promise<void>;

    sellProduct(
      _serialNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<void>;

    serialNumber(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "OwnershipTransferred(address,address)"(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;

    OwnershipTransferred(
      previousOwner?: string | null,
      newOwner?: string | null
    ): TypedEventFilter<
      [string, string],
      { previousOwner: string; newOwner: string }
    >;
  };

  estimateGas: {
    getHoneyInfo(
      _serialNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getProducerInfo(
      _producerAddress: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    modifyInfo(
      _serialNumber: BigNumberish,
      _quantityWeight: BigNumberish,
      _honeyType: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    permitAccess(
      _producerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    permitted(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    producePackage(
      _quantityWeight: BigNumberish,
      _honeyType: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    revokeAccess(
      _producerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    sellProduct(
      _serialNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    serialNumber(overrides?: CallOverrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    getHoneyInfo(
      _serialNumber: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getProducerInfo(
      _producerAddress: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    modifyInfo(
      _serialNumber: BigNumberish,
      _quantityWeight: BigNumberish,
      _honeyType: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    permitAccess(
      _producerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    permitted(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    producePackage(
      _quantityWeight: BigNumberish,
      _honeyType: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    revokeAccess(
      _producerAddress: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    sellProduct(
      _serialNumber: BigNumberish,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    serialNumber(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
